### PR TITLE
Check noise module dependencies with toposort

### PR DESCRIPTION
**Pull request by serin-delaunay**
* Add toposort dependency.
* Include license (Apache) in Windows distribution.
* Error if module names itself as a source or creates a circular dependency.
* Resolves https://github.com/Wangscape/Wangscape/issues/106.

To do:
- [x] Fix license download commands (AppVeyor's Start-FileDownload only works in PowerShell).
* ~Check that source modules exist.~ (issue #12)

### CODE REVIEW

**Comment by hryniuk** [comment]
How should it work? Can we have a test for it?

I've edited `Wangscape/doc/examples/example3/default_module_group.json` this way:
```
{
  "defaultoutputmodule":"OUTPUT",
  "modules":{
    "OUTPUT":{
      "type":"TranslatePoint",
      "Translation":[1.1,2.2,3.3],
      "SourceModule":"OUTPUT"
    },
    "perlin_clamped":{
      "type":"Clamp",
      "Bounds":[-1,1],
      "SourceModule":["perlin_clamped"]
    },
    "perlin":{
      "type":"Perlin",
      "OctaveCount":5,
      "Frequency":1,
      "Lacunarity":2,
      "Persistence":0.5,
      "NoiseQuality":"Fast"
    }
  }
}
```

and I get:
```shell
$ python wangcheck.py ../Wangscape/doc/examples/example3/example_options.json schemas
Checking "../Wangscape/doc/examples/example3/example_options.json"...
OK
```

What am I doing wrong?

**Comment by serin-delaunay** [comment]
`toposort` doesn't detect self-dependencies. try `import toposort` and `list(toposort.toposort({'a':{'b'}, 'b':{'a'}}))`, compared to `list(toposort.toposort({'a':{'a'}}))`. I tried a few different topological sort libraries, so I thought I'd chosen one which could detect that kind of error. I'll have to replace the library or add a separate check for self-dependency.

You've also pointed out another error: my code doesn't account for when `SourceModule` is a string rather than a list. I've pushed a fix for that.

**Comment by serin-delaunay** [comment]
Your example should error correctly now:
```
$ python wangcheck.py ../Wangscape/doc/examples/example2/example_options.json ../Wangscape/doc/schemas
Checking "../Wangscape/doc/examples/example2/example_options.json"...
Traceback (most recent call last):
  File "wangcheck.py", line 146, in <module>
    wc.check_all()
  File "wangcheck.py", line 130, in check_all
    self.check_module_groups()
  File "wangcheck.py", line 77, in check_module_groups
    self.check_module_dependencies(mg, fn)
  File "wangcheck.py", line 91, in check_module_dependencies
    raise CircularDependencyError({module_id:{module_id}})
toposort.CircularDependencyError: Circular dependencies exist among these items: {'perlin_clamped':{'perlin_clamped'}}
```

I can add tests, but I think that should be in a separate PR - there are a lot of other things that also need testing.

**Comment by hryniuk** [comment]
Yes, it works. I've used the example from https://github.com/Wangscape/Wangscape/issues/106

Ok, I'm merging it. Some tests could be also a good task for Hacktorberfest :).

**Pull request merged**
